title: Yang Guo
logo: https://gnuoyna.github.io/photo.jpg
theme: jekyll-theme-minimal
description: "Email: yangguo [at] cse [dot] cuhk [dot] edu [dot] hk <br><br><a href='https://scholar.google.com/citations?user=UP4tANkAAAAJ&&hl=en'>View My Google Scholar Profile</a>"
